name: Auto approve
on:
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  approve:
    name: "Approve PR"
    runs-on: ubuntu-20.04
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'
    permissions:
      pull-requests: write
    steps:
    # Currently there is no way to get the pull request number from the event payload in a workflow_run event.
    # We save it in the 'test' workflow.
    # This first step extracts it.
    # More information about it:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    - name: 'Download PR number'
      uses: actions/download-artifact@v3
      with:
        name: pr_number
    - run: unzip pr.zip
    - name: Get the PR value and set it in the environment
      run: |
        echo "PR_NUMBER=$(<pr_number.txt)" >> "$GITHUB_ENV"
        echo "Set PR_NUMBER to $PR_NUMBER"
    - uses: hmarr/auto-approve-action@v3
      with:
        pull-request-number: ${{ env.PR_NUMBER }}
    - run: gh workflow run "automerge" -f prNumber=${{ env.PR_NUMBER }}
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
